In [1]:
import pandas as pd

In [30]:
df = pd.read_csv(r'C:\Users\Dataشركه\Desktop\customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

## Calculate value counts for string columns

In [31]:
l = list(df.columns)
for col in l:
    if str(df[col].dtypes) =='object':
        print(df[col].value_counts(),f"\nNumber of {col} : ",df[col].nunique(),'\n')

Gender
Male      2652
Female    1248
Name: count, dtype: int64
Number of Gender :  2

Item Purchased
Blouse        171
Jewelry       171
Pants         171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Belt          161
Sunglasses    161
Coat          161
Sandals       160
Socks         159
Skirt         158
Shorts        157
Scarf         157
Hat           154
Handbag       153
Hoodie        151
Shoes         150
T-shirt       147
Sneakers      145
Boots         144
Backpack      143
Gloves        140
Jeans         124
Name: count, dtype: int64
Number of Item Purchased :  25

Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64
Number of Category :  4

Location
Montana           96
California        95
Idaho             93
Illinois          92
Alabama           89
Minnesota         88
Nebraska          87
New York          87
Nevada            87
Maryland          86
Delaware          86
Vermont           85
Louisiana         84
North Dakota      83
Missouri          81
West Virginia     81
New Mexico        81
Mississippi       80
Indiana           79
Georgia           79
Kentucky          79
Arkansas          79
North Carolina    78
Connecticut       78
Virginia          77
Ohio              77
Tennessee         77
Texas             77
Maine             77
South Carolina    76
Colorado          75
Oklahoma          75
Wisconsin         75
Oregon            74
Pennsylvania      74
Washington        73
Michigan          73
Alaska            72
Massachusetts     72
Wyoming           71
Utah              71
New Hampshire     71
South Dakota      70
Iowa              69
Florida           68
New Jersey        67
Hawaii            65
Arizona           65
Kansas            63
Rhode Island      63
Name: count, dtype: int64
Number of Location :  50

Size
M     1755
L     1053
S      663
XL     429
Name: count, dtype: int64
Number of Size :  4

Color
Olive        177
Yellow       174
Silver       173
Teal         172
Green        169
Black        167
Cyan         166
Violet       166
Gray         159
Maroon       158
Orange       154
Charcoal     153
Pink         153
Magenta      152
Blue         152
Purple       151
Peach        149
Red          148
Beige        147
Indigo       147
Lavender     147
Turquoise    145
White        142
Brown        141
Gold         138
Name: count, dtype: int64
Number of Color :  25

Season
Spring    999
Fall      975
Winter    971
Summer    955
Name: count, dtype: int64
Number of Season :  4

Subscription Status
No     2847
Yes    1053
Name: count, dtype: int64
Number of Subscription Status :  2

Shipping Type
Free Shipping     675
Standard          654
Store Pickup      650
Next Day Air      648
Express           646
2-Day Shipping    627
Name: count, dtype: int64
Number of Shipping Type :  6

Discount Applied
No     2223
Yes    1677
Name: count, dtype: int64
Number of Discount Applied :  2

Promo Code Used
No     2223
Yes    1677
Name: count, dtype: int64
Number of Promo Code Used :  2

Payment Method
PayPal           677
Credit Card      671
Cash             670
Debit Card       636
Venmo            634
Bank Transfer    612
Name: count, dtype: int64
Number of Payment Method :  6

Frequency of Purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64
Number of Frequency of Purchases :  7

## Perform initial data inspection (structure and missing values)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [33]:
df['Review Rating'].isna().sum()

np.int64(37)

## Handle review ratings for each category

In [34]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

## Convert "Frequency of Purchases" text values to numeric using mapping

In [35]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [36]:
df['Frequency of Purchases'].unique().tolist()

['Fortnightly',
 'Weekly',
 'Annually',
 'Quarterly',
 'Bi-Weekly',
 'Monthly',
 'Every 3 Months']

In [37]:
Frequency_map = {
    'Weekly':7,
    'Annually':365,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Monthly':30,
    'Every 3 Months':90,
    'Fortnightly':14
}

In [38]:
df['Frequency day']=df['Frequency of Purchases'].map(Frequency_map)

In [39]:
df['Frequency day']

0        14
1        14
2         7
3         7
4       365
       ...
3895      7
3896     14
3897     90
3898      7
3899     90
Name: Frequency day, Length: 3900, dtype: int64

## Clean and standardize column names formatting

In [40]:
df.columns= df.columns.str.replace(' ','_').str.lower()

In [41]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'frequency_day'],
      dtype='object')

In [42]:
df.to_excel('C:/Users/Dataشركه/Desktop/customer.xlsx' , index=False)

## What is the total revenue generated by male vs. female customers?

In [48]:
df.groupby('gender')[['purchase_amount']].sum()

        purchase_amount
gender
Female            75191
Male             157890

## Which customers used a discount but still spent more than the average purchase amount?

In [49]:
df[(df['purchase_amount'] > df['purchase_amount'].mean() ) & (df['discount_applied']=='Yes')][['customer_id','purchase_amount']]

      customer_id  purchase_amount
1               2               64
2               3               73
3               4               90
6               7               85
8               9               97
...           ...              ...
1666         1667               64
1670         1671               73
1672         1673               73
1673         1674               62
1675         1676               90

[839 rows x 2 columns]

## another way

In [50]:
df.query("discount_applied == 'Yes' and purchase_amount > purchase_amount.mean()")[['customer_id','purchase_amount']].head()

   customer_id  purchase_amount
1            2               64
2            3               73
3            4               90
6            7               85
8            9               97

## For customers with multiple orders, sum total purchase amounts and select those exceeding the overall mean who used discounts

In [23]:
g1=df[(df['discount_applied']=='Yes')].groupby('customer_id').agg(purchase_amount_sum = ('purchase_amount','sum')).reset_index()
m= df['purchase_amount'].mean()
g1[g1['purchase_amount_sum']>m]

      customer_id  purchase_amount_sum
1               2                   64
2               3                   73
3               4                   90
6               7                   85
8               9                   97
...           ...                  ...
1666         1667                   64
1670         1671                   73
1672         1673                   73
1673         1674                   62
1675         1676                   90

[839 rows x 2 columns]

## Which are the top 5 products with the highest average review rating?

In [24]:
df.groupby('item_purchased')['review_rating'].mean().round(2).sort_values(ascending=False).head(5).reset_index()

  item_purchased  review_rating
0         Gloves           3.86
1        Sandals           3.84
2          Boots           3.82
3            Hat           3.80
4        T-shirt           3.78

## Compare the average Purchase Amounts between Standard and Express Shipping.

In [25]:
shipping_type = ['Standard','Express']
df[df['shipping_type'].isin(shipping_type)].groupby('shipping_type')['purchase_amount'].mean().round(2).reset_index()

  shipping_type  purchase_amount
0       Express            60.48
1      Standard            58.46

## Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers

In [26]:
df.groupby('subscription_status').agg({'customer_id':'count',
                                      'purchase_amount':['sum','mean']}).round(2)

                    customer_id purchase_amount
                          count             sum   mean
subscription_status
No                         2847          170436  59.87
Yes                        1053           62645  59.49

## Which 5 products have the highest percentage of purchases with discounts applied?

In [51]:
df['discount_flag']= df['discount_applied'].apply(lambda x: 1 if x=='Yes' else 0)
resulte=df.groupby('item_purchased').agg(total_count=('item_purchased','count'),discount=('discount_flag','sum'))
resulte['dis']=(resulte['discount']/resulte['total_count'])*100
resulte=resulte.reset_index()

In [60]:
resulte[['item_purchased','dis']].sort_values('dis',ascending=False).head(5).round(2)

   item_purchased    dis
8             Hat  50.00
20       Sneakers  49.66
4            Coat  49.07
23        Sweater  48.17
13          Pants  47.37

In [28]:
g = df.groupby('item_purchased').agg({'item_purchased':'count','discount_flag':'sum'})
g['dis']= (g['discount_flag'])/g['item_purchased']*100
g.sort_values('dis',ascending=False).head(5).round(2)

                item_purchased  discount_flag    dis
item_purchased
Hat                        154             77  50.00
Sneakers                   145             72  49.66
Coat                       161             79  49.07
Sweater                    164             79  48.17
Pants                      171             81  47.37

## fast way

In [62]:
g2 = df.groupby("item_purchased")[['discount_flag']].mean().sort_values(by='discount_flag' ,ascending =False ).round(4).reset_index().head()
g2['discount_flag'] = g2['discount_flag']*100
g2

  item_purchased  discount_flag
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

## Segment customers into New, Returning, and Loyal based on their total  number of previous purchases, and show the count of each segment.

In [31]:
df['customer_segment']=df['previous_purchases'].apply(lambda x: 'new' if x<=1 else ('Returning' if x>=2 and x <=10 else 'Loyal'))

In [32]:
df['customer_segment'].value_counts().reset_index()

  customer_segment  count
0            Loyal   3116
1        Returning    701
2              new     83

### What are the top 3 most purchased products within each category?

In [45]:
top3 = df.groupby(['category','item_purchased'])['customer_id'].count().reset_index()
top3['rank']=top3.groupby(['category'])['customer_id'].rank(method='first', ascending=False)

In [46]:
top3[(top3['rank'] <=3)].sort_values(['category','rank'])

       category item_purchased  customer_id  rank
5   Accessories        Jewelry          171   1.0
1   Accessories           Belt          161   2.0
7   Accessories     Sunglasses          161   3.0
8      Clothing         Blouse          171   1.0
12     Clothing          Pants          171   2.0
13     Clothing          Shirt          169   3.0
20     Footwear        Sandals          160   1.0
21     Footwear          Shoes          150   2.0
22     Footwear       Sneakers          145   3.0
24    Outerwear         Jacket          163   1.0
23    Outerwear           Coat          161   2.0

### What are the top 3 most purchased products amounts within each category?

In [37]:
top3amount = df.groupby(['category','item_purchased'])['purchase_amount'].sum()
top3amount=top3amount.reset_index()
top3amount

       category item_purchased  purchase_amount
0   Accessories       Backpack             8636
1   Accessories           Belt             9635
2   Accessories         Gloves             8477
3   Accessories        Handbag             8857
4   Accessories            Hat             9375
5   Accessories        Jewelry            10010
6   Accessories          Scarf             9561
7   Accessories     Sunglasses             9649
8      Clothing         Blouse            10410
9      Clothing          Dress            10320
10     Clothing         Hoodie             8767
11     Clothing          Jeans             7548
12     Clothing          Pants            10090
13     Clothing          Shirt            10332
14     Clothing         Shorts             9433
15     Clothing          Skirt             9402
16     Clothing          Socks             9252
17     Clothing        Sweater             9462
18     Clothing        T-shirt             9248
19     Footwear          Boots             9018
20     Footwear        Sandals             9200
21     Footwear          Shoes             9240
22     Footwear       Sneakers             8635
23    Outerwear           Coat             9275
24    Outerwear         Jacket             9249

In [41]:
top3amount['rank'] = top3amount.groupby('category')['purchase_amount'].rank(method='first' , ascending=False)

In [42]:
top3amount[(top3amount['rank'] <= 3)].sort_values(['category','rank'])

       category item_purchased  purchase_amount  rank
5   Accessories        Jewelry            10010   1.0
7   Accessories     Sunglasses             9649   2.0
1   Accessories           Belt             9635   3.0
8      Clothing         Blouse            10410   1.0
13     Clothing          Shirt            10332   2.0
9      Clothing          Dress            10320   3.0
21     Footwear          Shoes             9240   1.0
20     Footwear        Sandals             9200   2.0
19     Footwear          Boots             9018   3.0
23    Outerwear           Coat             9275   1.0
24    Outerwear         Jacket             9249   2.0